<?php
/**
 * BoardMembershipWithOrganizationsInHierarchy
 *
 * PHP version 5
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Membercare API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@membercare.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Membercare\Client\Model;

use \ArrayAccess;
use \Membercare\Client\ObjectSerializer;

/**
 * BoardMembershipWithOrganizationsInHierarchy Class Doc Comment
 *
 * @category Class
 * @description Board membership bundled with a list of organizations that the board member has access to via this board membership
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BoardMembershipWithOrganizationsInHierarchy implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BoardMembershipWithOrganizationsInHierarchy';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'url' => 'string',
        'board_membership' => '\Membercare\Client\Model\BoardMembership',
        'organizations_with_propagated_board_member_category_roles' => '\Membercare\Client\Model\OrganizationWithPropagatedBoardMemberCategoryRoles[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'url' => null,
        'board_membership' => null,
        'organizations_with_propagated_board_member_category_roles' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'url' => 'url',
        'board_membership' => 'boardMembership',
        'organizations_with_propagated_board_member_category_roles' => 'organizationsWithPropagatedBoardMemberCategoryRoles'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'url' => 'setUrl',
        'board_membership' => 'setBoardMembership',
        'organizations_with_propagated_board_member_category_roles' => 'setOrganizationsWithPropagatedBoardMemberCategoryRoles'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'url' => 'getUrl',
        'board_membership' => 'getBoardMembership',
        'organizations_with_propagated_board_member_category_roles' => 'getOrganizationsWithPropagatedBoardMemberCategoryRoles'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['board_membership'] = isset($data['board_membership']) ? $data['board_membership'] : null;
        $this->container['organizations_with_propagated_board_member_category_roles'] = isset($data['organizations_with_propagated_board_member_category_roles']) ? $data['organizations_with_propagated_board_member_category_roles'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url The link to the current resource
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets board_membership
     *
     * @return \Membercare\Client\Model\BoardMembership
     */
    public function getBoardMembership()
    {
        return $this->container['board_membership'];
    }

    /**
     * Sets board_membership
     *
     * @param \Membercare\Client\Model\BoardMembership $board_membership board_membership
     *
     * @return $this
     */
    public function setBoardMembership($board_membership)
    {
        $this->container['board_membership'] = $board_membership;

        return $this;
    }

    /**
     * Gets organizations_with_propagated_board_member_category_roles
     *
     * @return \Membercare\Client\Model\OrganizationWithPropagatedBoardMemberCategoryRoles[]
     */
    public function getOrganizationsWithPropagatedBoardMemberCategoryRoles()
    {
        return $this->container['organizations_with_propagated_board_member_category_roles'];
    }

    /**
     * Sets organizations_with_propagated_board_member_category_roles
     *
     * @param \Membercare\Client\Model\OrganizationWithPropagatedBoardMemberCategoryRoles[] $organizations_with_propagated_board_member_category_roles Organizations with roles that the board member has access to via this board membership
     *
     * @return $this
     */
    public function setOrganizationsWithPropagatedBoardMemberCategoryRoles($organizations_with_propagated_board_member_category_roles)
    {
        $this->container['organizations_with_propagated_board_member_category_roles'] = $organizations_with_propagated_board_member_category_roles;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
