<?php
/**
 * QuestionDependencyCriteria
 *
 * PHP version 5
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Membercare API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@membercare.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Membercare\Client\Model;

use \ArrayAccess;
use \Membercare\Client\ObjectSerializer;

/**
 * QuestionDependencyCriteria Class Doc Comment
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuestionDependencyCriteria implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'QuestionDependencyCriteria';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'url' => 'string',
        'id' => 'int',
        'operator' => '\Membercare\Client\Model\QuestionDependencyCriteriaOperator',
        'answer_criteria_bool' => 'bool',
        'answer_criteria_number' => 'double',
        'answer_criteria_date_time' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'url' => null,
        'id' => 'int64',
        'operator' => null,
        'answer_criteria_bool' => null,
        'answer_criteria_number' => 'double',
        'answer_criteria_date_time' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'url' => 'url',
        'id' => 'id',
        'operator' => 'operator',
        'answer_criteria_bool' => 'answerCriteriaBool',
        'answer_criteria_number' => 'answerCriteriaNumber',
        'answer_criteria_date_time' => 'answerCriteriaDateTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'url' => 'setUrl',
        'id' => 'setId',
        'operator' => 'setOperator',
        'answer_criteria_bool' => 'setAnswerCriteriaBool',
        'answer_criteria_number' => 'setAnswerCriteriaNumber',
        'answer_criteria_date_time' => 'setAnswerCriteriaDateTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'url' => 'getUrl',
        'id' => 'getId',
        'operator' => 'getOperator',
        'answer_criteria_bool' => 'getAnswerCriteriaBool',
        'answer_criteria_number' => 'getAnswerCriteriaNumber',
        'answer_criteria_date_time' => 'getAnswerCriteriaDateTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['operator'] = isset($data['operator']) ? $data['operator'] : null;
        $this->container['answer_criteria_bool'] = isset($data['answer_criteria_bool']) ? $data['answer_criteria_bool'] : null;
        $this->container['answer_criteria_number'] = isset($data['answer_criteria_number']) ? $data['answer_criteria_number'] : null;
        $this->container['answer_criteria_date_time'] = isset($data['answer_criteria_date_time']) ? $data['answer_criteria_date_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url The link to the current resource
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The question ID
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets operator
     *
     * @return \Membercare\Client\Model\QuestionDependencyCriteriaOperator
     */
    public function getOperator()
    {
        return $this->container['operator'];
    }

    /**
     * Sets operator
     *
     * @param \Membercare\Client\Model\QuestionDependencyCriteriaOperator $operator operator
     *
     * @return $this
     */
    public function setOperator($operator)
    {
        $this->container['operator'] = $operator;

        return $this;
    }

    /**
     * Gets answer_criteria_bool
     *
     * @return bool
     */
    public function getAnswerCriteriaBool()
    {
        return $this->container['answer_criteria_bool'];
    }

    /**
     * Sets answer_criteria_bool
     *
     * @param bool $answer_criteria_bool The answer criteria used when answer type is bool
     *
     * @return $this
     */
    public function setAnswerCriteriaBool($answer_criteria_bool)
    {
        $this->container['answer_criteria_bool'] = $answer_criteria_bool;

        return $this;
    }

    /**
     * Gets answer_criteria_number
     *
     * @return double
     */
    public function getAnswerCriteriaNumber()
    {
        return $this->container['answer_criteria_number'];
    }

    /**
     * Sets answer_criteria_number
     *
     * @param double $answer_criteria_number The answer criteria used when answer type is number
     *
     * @return $this
     */
    public function setAnswerCriteriaNumber($answer_criteria_number)
    {
        $this->container['answer_criteria_number'] = $answer_criteria_number;

        return $this;
    }

    /**
     * Gets answer_criteria_date_time
     *
     * @return \DateTime
     */
    public function getAnswerCriteriaDateTime()
    {
        return $this->container['answer_criteria_date_time'];
    }

    /**
     * Sets answer_criteria_date_time
     *
     * @param \DateTime $answer_criteria_date_time The answer criteria used when answer type is date time
     *
     * @return $this
     */
    public function setAnswerCriteriaDateTime($answer_criteria_date_time)
    {
        $this->container['answer_criteria_date_time'] = $answer_criteria_date_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
