<?php
/**
 * ArrangementSearchCriteriaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Membercare API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@membercare.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Membercare\Client;

use PHPUnit\Framework\TestCase;

/**
 * ArrangementSearchCriteriaTest Class Doc Comment
 *
 * @category    Class
 * @description The representation of an Arrangement Search Criteria
 * @package     Membercare\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ArrangementSearchCriteriaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ArrangementSearchCriteria"
     */
    public function testArrangementSearchCriteria()
    {
    }

    /**
     * Test attribute "starts_after"
     */
    public function testPropertyStartsAfter()
    {
    }

    /**
     * Test attribute "ends_before"
     */
    public function testPropertyEndsBefore()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "sub_categories"
     */
    public function testPropertySubCategories()
    {
    }

    /**
     * Test attribute "sections"
     */
    public function testPropertySections()
    {
    }

    /**
     * Test attribute "areas"
     */
    public function testPropertyAreas()
    {
    }

    /**
     * Test attribute "include_non_enrollable"
     */
    public function testPropertyIncludeNonEnrollable()
    {
    }

    /**
     * Test attribute "include_cancelled"
     */
    public function testPropertyIncludeCancelled()
    {
    }

    /**
     * Test attribute "only_web_enabled"
     */
    public function testPropertyOnlyWebEnabled()
    {
    }

    /**
     * Test attribute "for_invitees_only"
     */
    public function testPropertyForInviteesOnly()
    {
    }

    /**
     * Test attribute "attendance_registration_enabled"
     */
    public function testPropertyAttendanceRegistrationEnabled()
    {
    }

    /**
     * Test attribute "attendance_registration_completed"
     */
    public function testPropertyAttendanceRegistrationCompleted()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }

    /**
     * Test attribute "custom_field_values_match"
     */
    public function testPropertyCustomFieldValuesMatch()
    {
    }

    /**
     * Test attribute "organizations"
     */
    public function testPropertyOrganizations()
    {
    }

    /**
     * Test attribute "include_recurring_course_recurrences"
     */
    public function testPropertyIncludeRecurringCourseRecurrences()
    {
    }
}
