<?php
/**
 * DebtorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Membercare API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@membercare.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Membercare\Client;

use PHPUnit\Framework\TestCase;

/**
 * DebtorTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a person or a company
 * @package     Membercare\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DebtorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Debtor"
     */
    public function testDebtor()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "debtor_account_number"
     */
    public function testPropertyDebtorAccountNumber()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }

    /**
     * Test attribute "invoices_link"
     */
    public function testPropertyInvoicesLink()
    {
    }

    /**
     * Test attribute "member_type"
     */
    public function testPropertyMemberType()
    {
    }

    /**
     * Test attribute "default_payer_link"
     */
    public function testPropertyDefaultPayerLink()
    {
    }

    /**
     * Test attribute "dafualt_payer_rule"
     */
    public function testPropertyDafualtPayerRule()
    {
    }

    /**
     * Test attribute "close_date"
     */
    public function testPropertyCloseDate()
    {
    }

    /**
     * Test attribute "einvoice_ean"
     */
    public function testPropertyEinvoiceEan()
    {
    }

    /**
     * Test attribute "einvoice_email"
     */
    public function testPropertyEinvoiceEmail()
    {
    }

    /**
     * Test attribute "close_reason"
     */
    public function testPropertyCloseReason()
    {
    }

    /**
     * Test attribute "default_address_type"
     */
    public function testPropertyDefaultAddressType()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "last_change"
     */
    public function testPropertyLastChange()
    {
    }

    /**
     * Test attribute "finance_type"
     */
    public function testPropertyFinanceType()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "email_for_invoices"
     */
    public function testPropertyEmailForInvoices()
    {
    }

    /**
     * Test attribute "business_numbers"
     */
    public function testPropertyBusinessNumbers()
    {
    }

    /**
     * Test attribute "invoice_distribution_preference"
     */
    public function testPropertyInvoiceDistributionPreference()
    {
    }

    /**
     * Test attribute "social_security_number"
     */
    public function testPropertySocialSecurityNumber()
    {
    }

    /**
     * Test attribute "anonymized_on"
     */
    public function testPropertyAnonymizedOn()
    {
    }

    /**
     * Test attribute "honorific"
     */
    public function testPropertyHonorific()
    {
    }

    /**
     * Test attribute "name1"
     */
    public function testPropertyName1()
    {
    }

    /**
     * Test attribute "name2"
     */
    public function testPropertyName2()
    {
    }

    /**
     * Test attribute "memberships"
     */
    public function testPropertyMemberships()
    {
    }

    /**
     * Test attribute "send_invoices_to"
     */
    public function testPropertySendInvoicesTo()
    {
    }

    /**
     * Test attribute "send_mail_to"
     */
    public function testPropertySendMailTo()
    {
    }
}
