<?php
/**
 * LedgerItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Membercare API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@membercare.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Membercare\Client;

use PHPUnit\Framework\TestCase;

/**
 * LedgerItemTest Class Doc Comment
 *
 * @category    Class
 * @description LedgerItem
 * @package     Membercare\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LedgerItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LedgerItem"
     */
    public function testLedgerItem()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "accounting_type"
     */
    public function testPropertyAccountingType()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "income_date"
     */
    public function testPropertyIncomeDate()
    {
    }

    /**
     * Test attribute "approved"
     */
    public function testPropertyApproved()
    {
    }

    /**
     * Test attribute "revision_number"
     */
    public function testPropertyRevisionNumber()
    {
    }

    /**
     * Test attribute "line_type"
     */
    public function testPropertyLineType()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "journal_id"
     */
    public function testPropertyJournalId()
    {
    }

    /**
     * Test attribute "finance_dimensions"
     */
    public function testPropertyFinanceDimensions()
    {
    }

    /**
     * Test attribute "payer_debtor_account_number"
     */
    public function testPropertyPayerDebtorAccountNumber()
    {
    }

    /**
     * Test attribute "invoice_id"
     */
    public function testPropertyInvoiceId()
    {
    }

    /**
     * Test attribute "invoice_item_id"
     */
    public function testPropertyInvoiceItemId()
    {
    }

    /**
     * Test attribute "payment_info"
     */
    public function testPropertyPaymentInfo()
    {
    }
}
