<?php
/**
 * MethodAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Membercare API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@membercare.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Membercare\Client;

use PHPUnit\Framework\TestCase;

/**
 * MethodAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description 0 &#x3D; ReuseSlot  1 &#x3D; Private  2 &#x3D; FamANDAssem  3 &#x3D; Assembly  4 &#x3D; Family  5 &#x3D; FamORAssem  6 &#x3D; Public  7 &#x3D; MemberAccessMask  8 &#x3D; UnmanagedExport  16 &#x3D; Static  32 &#x3D; Final  64 &#x3D; Virtual  128 &#x3D; HideBySig  256 &#x3D; VtableLayoutMask  512 &#x3D; CheckAccessOnOverride  1024 &#x3D; Abstract  2048 &#x3D; SpecialName  4096 &#x3D; RTSpecialName  8192 &#x3D; PinvokeImpl  16384 &#x3D; HasSecurity  32768 &#x3D; RequireSecObject  53248 &#x3D; ReservedMask
 * @package     Membercare\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MethodAttributesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MethodAttributes"
     */
    public function testMethodAttributes()
    {
    }
}
