<?php
/**
 * PersonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Membercare API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@membercare.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Membercare\Client;

use PHPUnit\Framework\TestCase;

/**
 * PersonTest Class Doc Comment
 *
 * @category    Class
 * @description Representation of a Person for exposure in the WebApi
 * @package     Membercare\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PersonTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Person"
     */
    public function testPerson()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "debtor_account_number"
     */
    public function testPropertyDebtorAccountNumber()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }

    /**
     * Test attribute "invoices_link"
     */
    public function testPropertyInvoicesLink()
    {
    }

    /**
     * Test attribute "member_type"
     */
    public function testPropertyMemberType()
    {
    }

    /**
     * Test attribute "default_payer_link"
     */
    public function testPropertyDefaultPayerLink()
    {
    }

    /**
     * Test attribute "dafualt_payer_rule"
     */
    public function testPropertyDafualtPayerRule()
    {
    }

    /**
     * Test attribute "close_date"
     */
    public function testPropertyCloseDate()
    {
    }

    /**
     * Test attribute "einvoice_ean"
     */
    public function testPropertyEinvoiceEan()
    {
    }

    /**
     * Test attribute "einvoice_email"
     */
    public function testPropertyEinvoiceEmail()
    {
    }

    /**
     * Test attribute "close_reason"
     */
    public function testPropertyCloseReason()
    {
    }

    /**
     * Test attribute "default_address_type"
     */
    public function testPropertyDefaultAddressType()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "last_change"
     */
    public function testPropertyLastChange()
    {
    }

    /**
     * Test attribute "finance_type"
     */
    public function testPropertyFinanceType()
    {
    }

    /**
     * Test attribute "relations_link"
     */
    public function testPropertyRelationsLink()
    {
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "age"
     */
    public function testPropertyAge()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "name_history"
     */
    public function testPropertyNameHistory()
    {
    }

    /**
     * Test attribute "honorific"
     */
    public function testPropertyHonorific()
    {
    }

    /**
     * Test attribute "custom_field_values_link"
     */
    public function testPropertyCustomFieldValuesLink()
    {
    }

    /**
     * Test attribute "memberships_link"
     */
    public function testPropertyMembershipsLink()
    {
    }

    /**
     * Test attribute "boardmemberships_link"
     */
    public function testPropertyBoardmembershipsLink()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "web_user_id"
     */
    public function testPropertyWebUserId()
    {
    }

    /**
     * Test attribute "social_security_number"
     */
    public function testPropertySocialSecurityNumber()
    {
    }

    /**
     * Test attribute "internal_user_info"
     */
    public function testPropertyInternalUserInfo()
    {
    }

    /**
     * Test attribute "external_system_info"
     */
    public function testPropertyExternalSystemInfo()
    {
    }

    /**
     * Test attribute "login_token"
     */
    public function testPropertyLoginToken()
    {
    }

    /**
     * Test attribute "allow_sms"
     */
    public function testPropertyAllowSms()
    {
    }

    /**
     * Test attribute "allow_email"
     */
    public function testPropertyAllowEmail()
    {
    }

    /**
     * Test attribute "union_representatives"
     */
    public function testPropertyUnionRepresentatives()
    {
    }

    /**
     * Test attribute "union_groups"
     */
    public function testPropertyUnionGroups()
    {
    }

    /**
     * Test attribute "employments"
     */
    public function testPropertyEmployments()
    {
    }

    /**
     * Test attribute "memberships"
     */
    public function testPropertyMemberships()
    {
    }

    /**
     * Test attribute "board_memberships"
     */
    public function testPropertyBoardMemberships()
    {
    }

    /**
     * Test attribute "identity"
     */
    public function testPropertyIdentity()
    {
    }

    /**
     * Test attribute "anonymized_on"
     */
    public function testPropertyAnonymizedOn()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "consents"
     */
    public function testPropertyConsents()
    {
    }

    /**
     * Test attribute "accepted_terms"
     */
    public function testPropertyAcceptedTerms()
    {
    }

    /**
     * Test attribute "foreign_system_mappings"
     */
    public function testPropertyForeignSystemMappings()
    {
    }

    /**
     * Test attribute "preferred_address"
     */
    public function testPropertyPreferredAddress()
    {
    }

    /**
     * Test attribute "preferred_contact"
     */
    public function testPropertyPreferredContact()
    {
    }

    /**
     * Test attribute "salary_system_identification"
     */
    public function testPropertySalarySystemIdentification()
    {
    }

    /**
     * Test attribute "temporary"
     */
    public function testPropertyTemporary()
    {
    }

    /**
     * Test attribute "interests"
     */
    public function testPropertyInterests()
    {
    }

    /**
     * Test attribute "bank_registration_number"
     */
    public function testPropertyBankRegistrationNumber()
    {
    }

    /**
     * Test attribute "bank_account_number"
     */
    public function testPropertyBankAccountNumber()
    {
    }

    /**
     * Test attribute "profile_picture_identification"
     */
    public function testPropertyProfilePictureIdentification()
    {
    }
}
