<?php
/**
 * CommunityGroupApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Membercare API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@membercare.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Membercare\Client;

use Membercare\Client\Configuration;
use Membercare\Client\ApiException;
use Membercare\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CommunityGroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  Membercare\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CommunityGroupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCommunityFileChanges
     *
     * Get a paged result of community files changes for all groups..
     *
     */
    public function testGetCommunityFileChanges()
    {
    }

    /**
     * Test case for getCommunityFileChangesByGroup
     *
     * Get a paged result of community file changes for the chosen group..
     *
     */
    public function testGetCommunityFileChangesByGroup()
    {
    }

    /**
     * Test case for getCommunityGroup
     *
     * Get a community group with origin.
     *
     */
    public function testGetCommunityGroup()
    {
    }

    /**
     * Test case for getCommunityGroupAnnouncementChanges
     *
     * Get a paged result of community group announcement changes for all groups..
     *
     */
    public function testGetCommunityGroupAnnouncementChanges()
    {
    }

    /**
     * Test case for getCommunityGroupAnnouncementChangesByGroup
     *
     * Get a paged result of community group announcement changes for the chosen group..
     *
     */
    public function testGetCommunityGroupAnnouncementChangesByGroup()
    {
    }

    /**
     * Test case for getCommunityGroupMeetingChanges
     *
     * Get a paged result of community group meeting changes for all groups..
     *
     */
    public function testGetCommunityGroupMeetingChanges()
    {
    }

    /**
     * Test case for getCommunityGroupMeetingChangesByGroup
     *
     * Get a paged result of community group meeting changes for the chosen group..
     *
     */
    public function testGetCommunityGroupMeetingChangesByGroup()
    {
    }

    /**
     * Test case for getCommunityGroupMembers
     *
     * Get members of a community group.
     *
     */
    public function testGetCommunityGroupMembers()
    {
    }

    /**
     * Test case for getCommunityGroupMessageChanges
     *
     * Get a paged result of community group message changes for all groups..
     *
     */
    public function testGetCommunityGroupMessageChanges()
    {
    }

    /**
     * Test case for getCommunityGroupMessageChangesByGroup
     *
     * Get a paged result of community group message changes for the chosen group..
     *
     */
    public function testGetCommunityGroupMessageChangesByGroup()
    {
    }

    /**
     * Test case for getCommunityGroups
     *
     * Get a paged result of community groups with origin.
     *
     */
    public function testGetCommunityGroups()
    {
    }
}
